<?
$aMenuLinks = Array(
    Array(
        "Автопарк", 
        "/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Услуги", 
        "services/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Способы оплаты", 
        "pay/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "О компании", 
        "about/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Контакты", 
        "contacts/", 
        Array(), 
        Array(), 
        "" 
    )
);
?>